### ISSUE TITLE
Differences in method names between huawei and google maps sdk

### ISSUE THREAD

**Issue by TomBruyneel** [johnthiriet/Xamarin.Android.Huawei.Hms#2]
While converting a project from google maps to huawei maps (thanks for your excellent work btw), I noticed following differences on the MarkerOptions object:

Position instead of SetPosition
Title instead of SetTitle
Snippet instead of SetSnippet

I would prefer those functions to be replaced with properties in both sdk's, but as that will not happen it might be better to follow the xamarin google maps bindings?

Anyway, thanks for your work, this has made my job incredibly easier!

**Comment by johnthiriet** [comment]
Hi, thanks for your comment.
I was actually busy working on bindings for the HMS v5 SDKs.
While I was at it, I applied your suggestions in the rc1 of those packages :-)
Please give it a try and tell me what you think about them. (Do not forget to activate nuget previews).
